name: Develop Build

on: 
  push:
    branches:
      - develop

jobs:
  publish:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup DotNet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Build
        run: dotnet build PterodactylDotNet/PterodactylDotNet.csproj -c Release